[project]
name = "kasir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "jinja2>=3.1.6",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.35.0",
]
